config/routes.rb
ForemanImageBuilder::Engine.routes.draw do
  resources :blueprints, only: [:index, :new, :create] do
    member do
      post 'build'
    end
  end
  resources :images, only: [:index] do
    member do
      post 'sync'
      get 'predeploy'
      post 'deploy'
    end
  end
  get 'welcome', to: '/react#index', as: 'welcome'
end

Foreman::Application.routes.draw do
  mount ForemanImageBuilder::Engine, at: '/foreman_image_builder'
end

app/models/concerns/foreman_image_builder/host_extensions.rb
module ForemanImageBuilder
  module HostExtensions
    extend ActiveSupport::Concern

    included do
      # execute callbacks
    end

    # create or overwrite instance methods...
    def instance_method_name
    end

    module ClassMethods
      # create or overwrite class methods...
      def class_method_name
      end
    end
  end
end

app/models/concerns/foreman_plugin_template/host_extensions.rb
module ForemanPluginTemplate
  module HostExtensions
    extend ActiveSupport::Concern

    included do
      # execute callbacks
    end

    # create or overwrite instance methods...
    def instance_method_name
    end

    module ClassMethods
      # create or overwrite class methods...
      def class_method_name
      end
    end
  end
end

app/models/foreman_image_builder/blueprint.rb
module ForemanImageBuilder
  class Blueprint
    include ActiveModel::Model
    include ActiveModel::Attributes

    attribute :name, :string
    attribute :description, :string
    attribute :distro, :string
    attribute :version, :string
    attribute :packages, array: true
    attribute :modules, array: true
    attribute :groups, array: true
    attribute :customizations, :string

    def self.any?
      true
    end

    def id
      name
    end

    def to_param
      name
    end

    def customizations=(value)
      super value.to_json
    end

    def customizations
      JSON.parse(super)
    end
  end
end

app/models/foreman_image_builder/image_deployment.rb
module ForemanImageBuilder
  class ImageDeployment
    extend ActiveModel::Naming
    # include ActiveModel::API
    include ActiveModel::Conversion

    attr_accessor :image_id, :system_name

    def self.any?
      true
    end

    def to_key
      image_id && [image_id]
    end

    def initialize(args = {})
      @image_id = args[:image_id]
    end
  end
end

app/controllers/foreman_image_builder/blueprints_controller.rb
class ForemanImageBuilder::BlueprintsController < ::ApplicationController
  def index
    @proxies = ::SmartProxy.with_features('Images')
    @images = {}
    @blueprints = {}
    @proxies.each do |proxy|
      bp_api = ForemanImageBuilder::Blueprints.new(url: proxy.url)
      @images[proxy.id] = bp_api.list_images.group_by { |image| image["blueprint"] }
      @blueprints[proxy.id] = bp_api.all
    end
  end

  def new
    @blueprint = ForemanImageBuilder::Blueprint.new
  end

  def create
    blueprint = ForemanImageBuilder::Blueprint.new(blueprint_params)
    ForemanImageBuilder::Blueprints.new(url: ::SmartProxy.all.first.url).create(blueprint)
    redirect_to blueprints_path
  end

  def build
    ForemanImageBuilder::Blueprints.new(url: ::SmartProxy.all.first.url).build(params[:id])
    redirect_to blueprints_path
  end

  private
    def blueprint_params
      params.require(:blueprint).permit(:name, :description, :packages, :customizations)
    end
end

app/controllers/foreman_image_builder/images_controller.rb
class ForemanImageBuilder::ImagesController < ApplicationController
  def index
    @proxies = ::SmartProxy.with_features('Images')
    @images = ForemanImageBuilder::Blueprints.new(url: ::SmartProxy.all.first.url).list_images
  end

  def sync
    # TODO: Allow custom image name
    ForemanImageBuilder::Blueprints.new(url: ::SmartProxy.all.first.url).sync_image("Fedora", params[:id])
    redirect_to images_path
  end

  def predeploy
    # TODO: Verify existence of image
    @deployment = ForemanImageBuilder::ImageDeployment.new(image_id: params[:id])
    @systems = ForemanImageBuilder::Blueprints.new(url: ::SmartProxy.all.first.url).list_systems

    pp @systems
  end

  def deploy
    ForemanImageBuilder::Blueprints.new(url: ::SmartProxy.all.first.url).deploy_system(params[:system_name], params[:id])
    redirect_to images_path
  end
end

app/helpers/concerns/foreman_image_builder/hosts_helper_extensions.rb
module ForemanImageBuilder
  module HostsHelperExtensions
    extend ActiveSupport::Concern

    included do
      # execute callbacks
    end

    # create or overwrite instance methods...
    def instance_method_name
    end
  end
end

app/helpers/concerns/foreman_plugin_template/hosts_helper_extensions.rb
module ForemanPluginTemplate
  module HostsHelperExtensions
    extend ActiveSupport::Concern

    included do
      # execute callbacks
    end

    # create or overwrite instance methods...
    def instance_method_name
    end
  end
end

app/helpers/foreman_image_builder/blueprints_helper.rb
module ForemanImageBuilder
  module BlueprintsHelper
    def permitted_blueprint_actions(blueprint)
      actions = []
      # actions << link_to(_("Edit"), edit_foreman_image_builder_blueprint_path(blueprint))
      # actions << link_to(_("Delete"), foreman_image_builder_blueprint_path(blueprint), method: :delete, data: { confirm: _("Are you sure you want to delete this blueprint?") })
      actions << link_to(_("Build"), foreman_image_builder.build_blueprint_path(blueprint.to_param), method: :post, data: { confirm: _("Are you sure you want to build this blueprint?") })
      actions
    end
  end
end

app/views/dashboard/_foreman_image_builder_widget.html.erb
<h4 class="header ca"><%= _('ForemanPluginTemplate') %></h4>
<%= _('Widget content') %>

app/views/dashboard/_foreman_plugin_template_widget.html.erb
<h4 class="header ca"><%= _('ForemanPluginTemplate') %></h4>
<%= _('Widget content') %>

app/views/foreman_image_builder/blueprints/index.html.erb
<% title "Blueprints" %>

<%= title_actions new_link(_("Create Blueprint"), engine: foreman_image_builder) %>

<table class="<%= table_css_classes 'table-fixed' %>">
  <thead>
    <tr>
      <th><%= _('Smart Proxy') %></th>
      <th><%= _('Name') %></th>
      <th><%= _('Images') %></th>
      <th class="col-md-1"><%= _('Actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @proxies.each do |proxy| %>
      <% (@blueprints[proxy.id] || []).each do |blueprint| %>
        <tr>
          <td><%= proxy.name %></td>
          <td><%= blueprint.name %></td>
          <td><%= @images[proxy.id].fetch(blueprint.name, []).size %></td>
          <td><%= action_buttons(*permitted_blueprint_actions(blueprint)) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/foreman_image_builder/blueprints/new.html.erb
<%= form_for(@blueprint, url: blueprints_path, method: :post) do |form| %>
  <%= text_f form, :name %>
  <%= textarea_f form, :description %>
  <%= textarea_f form, :packages %>
  <%= textarea_f form, :customizations %>
  <%= submit_or_cancel form %>
<% end %>

app/views/foreman_image_builder/images/index.html.erb
<% title "Images" %>

<table class="<%= table_css_classes 'table-fixed' %>">
  <thead>
    <tr>
      <th><%= _('Blueprint') %></th>
      <th>ID</th>
      <th><%= _('Built') %></th>
      <th class="col-md-1"><%= _('Actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image["blueprint"] %></td>
        <td><%= image["id"] %></td>
        <td><%= time_ago_in_words(Time.at(image["job_created"])) %></td>
        <td>
          <%= link_to(_("Synchronize"), foreman_image_builder.sync_image_path(image["id"]), method: :post, data: { confirm: _("Are you sure you want to sync this image?") }) %>
          <%= link_to(_("Deploy"), foreman_image_builder.predeploy_image_path(image["id"])) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/foreman_image_builder/images/predeploy.html.erb
About to deploy <%= @deployment.image_id %>

<%= form_for(@deployment, url: deploy_image_path, method: :post) do |form| %>
  <%= form_select_f form, :system_name, @systems.map { |system| [system["Name"], system["Name"]] } %>

  <%= submit_or_cancel form, false, button_text: _("Deploy") %>
<% end %>